spring.application.name=tts
server.port=17010
server.servlet.context-path=/vision-mind-tts

tts.model-root=resource/tts/model
tts.default-model=sherpa-onnx-vits-zh-ll
tts.runtime-java-jar=auto
tts.runtime-native-jar=auto
tts.runtime-provider=cpu
tts.num-threads=2
tts.default-speaker-id=0
tts.max-input-length=300
tts.default-speed=1.0
tts.silence-scale=0.2
tts.vits-length-scale=1.0
tts.vits-noise-scale=0.667
tts.vits-noise-scale-w=0.8
