spring:
  application:
    name: reid

server:
  port: 17004
  servlet:
    context-path: /vision-mind-reid

vision-mind:
  resource:
    root: ./resource
    fallback-env: VISION_MIND_PATH
    validate-on-startup: true
    manifest: resource/manifest.json
  native:
    dll-path: /lib/opencv/opencv_java490.dll
    so-path: /lib/opencv/libopencv_java4100.so
    use-gpu: false
  native-load:
    skip-open-cv: ${vision-mind.skip-opencv:false}
  runtime:
    profile: default
  reid:
    model:
      onnx: /reid/model/AGW_R50-ibn-bn.onnx
    matrix-path: /reid/projectionMatrix.bin
    vector-store:
      mode: memory
      lucene-path: /data/reidIndex
      elasticsearch:
        uris: http://127.0.0.1:9200
        username: ''
        password: ''
        api-key: ''
        index: vision_mind_reid
  common:
    matrix-path: /reid/projectionMatrix.bin
  yolo:
    default-types: [0, 1, 2, 3, 4, 5, 6, 7, 8]
    obb-default-types: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
