spring:
  application:
    name: asr
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 17008
  servlet:
    context-path: /vision-mind-asr

vision-mind:
  resource:
    root: ./resource
    fallback-env: VISION_MIND_PATH
    validate-on-startup: true
    manifest: resource/manifest.json
  native-load:
    skip-open-cv: ${vision-mind.skip-opencv:false}
  runtime:
    profile: default
  vector-store:
    mode: memory
  asr:
    model-dir: resource/asr/model/sherpa-onnx-streaming-zipformer-zh-fp16-2025-06-30
    punctuation-model-dir: resource/asr/model/sherpa-onnx-punct-ct-transformer-zh-en-vocab272727-2024-04-12-int8
    config-dir: resource/asr/config
    upload-dir: resource/asr/uploads
    hotwords-dir: resource/asr/model/sherpa-onnx-streaming-zipformer-zh-fp16-2025-06-30/.hotwords
    runtime-java-jar: auto
    runtime-native-jar: auto
    runtime-provider: cpu
    num-threads: 2
    hotwords-score: 1.5
    decoding-method: modified_beam_search
