spring.application.name=asr
server.port=17008
server.servlet.context-path=/vision-mind-asr
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

vision-mind.asr.model-dir=resource/asr/model/sherpa-onnx-streaming-zipformer-zh-fp16-2025-06-30
vision-mind.asr.punctuation-model-dir=resource/asr/model/sherpa-onnx-punct-ct-transformer-zh-en-vocab272727-2024-04-12-int8
vision-mind.asr.config-dir=resource/asr/config
vision-mind.asr.upload-dir=resource/asr/uploads
vision-mind.asr.hotwords-dir=resource/asr/model/sherpa-onnx-streaming-zipformer-zh-fp16-2025-06-30/.hotwords
vision-mind.asr.runtime-java-jar=auto
vision-mind.asr.runtime-native-jar=auto
vision-mind.asr.runtime-provider=cpu
vision-mind.asr.num-threads=2
vision-mind.asr.hotwords-score=1.5
vision-mind.asr.decoding-method=modified_beam_search
