spring:
  application:
    name: tbir
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 17003
  address: 0.0.0.0
  servlet:
    context-path: /vision-mind-tbir

vision-mind:
  resource:
    root: ./resource
    fallback-env: VISION_MIND_PATH
    validate-on-startup: true
    manifest: resource/manifest.json
  native-load:
    skip-open-cv: ${vision-mind.skip-opencv:false}
  runtime:
    profile: default
  vector-store:
    mode: ${vector.store.mode:memory}

component:
  path: ..
img:
  onnx: /tbir/model/clip-vit-b32-img.onnx
text:
  onnx: /tbir/model/clip-vit-b32-text.onnx
clip:
  tokenizer: /tbir/clip-tokenizer
open:
  detect: true
detect:
  types: yolo,sam
filter:
  box:
    size: 50,300
augment:
  types: original,flipH,rotate15,rotate-15,blur,bright,contrast
key:
  expand:
    num: 5
